{
 "title": "Nixer Plugin",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "action",
    "label": "Action",
    "query": "show tag values from recaptcha with key = action"
   }
  ]
 },
 "panels": [
  { "title": "Login", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Login",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Success",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "login",
     "query": "SELECT sum(\"value\") FROM \"login\" WHERE (\"result\" = 'success') AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "success" }
     ]
    },
    {
     "alias": "Failures",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "login",
     "query": "SELECT sum(\"value\") FROM \"login\" WHERE (\"result\" = 'success') AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "failed" }
     ]
    }
   ]
  },
  {
   "title": "Login Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "FAILED: $tag_reason",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "reason" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "login",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "failed" }
     ]
    }
   ]
  },
  { "title": "Captcha", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "action" },
  {
   "title": "Recaptcha $action",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "repeat": "action",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Passed",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "recaptcha",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "passed" },
      { "condition": "AND", "key": "action", "operator": "=~", "value": "/^$action$/" }
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "recaptcha",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "failed" },
      { "condition": "AND", "key": "action", "operator": "=~", "value": "/^$action$/" }
     ]
    }
   ]
  }
 ]
}