name: Testspace
on:
  push:
    branches:
      - ci/testspace-trigger
jobs:
  export-core:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          - name: Testspace client install & config
            uses: testspace-com/setup-testspace@v1
            with:
              domain: ${{github.repository_owner}}
          - name: Testspace push test content
            run: testspace "[${{ github.workflow }}/${{ github.job}}]./core/build/test-results/test/*.xml"